name = "StringAlgebraLinfinity"
version = "0.1.0"
defaultTargets = ["StringAlgebra.Linfinity"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "StringAlgebra"
